import type {
  BakeProgressListener,
  RasterBakeArtifact,
  RasterBakeRequest,
  RasterBakerModule,
  SerializedBakeError,
} from '../bake.js';
import {
  createDirectRasterBakerFromInstance,
  instantiateWasm,
  type DirectRasterBakerAbi,
} from '../internal/raster-baker-wasm.js';
// The ABI module is generated by the Rust `generate-mtsdf-abi` bin target, so its exported names are not ours to
// move; alias them at the boundary instead.
import { mtsdfBakerAbi as msdfBakerAbi } from '../generated/mtsdf-baker-abi.js';
import { compileWasmResponse } from '../internal/compile-wasm-response.js';
import { cacheSuccessfulPromise } from '../internal/successful-promise-cache.js';
import {
  MSDF_EXTENSION,
  MSDF_FORMAT_VERSION,
  MSDF_KIND,
  msdfDescriptor,
  type MsdfOptions,
  type MsdfDescriptor,
} from '../internal/msdf-contract.js';
import { GlyphError } from '../glyph-error.js';
import type { Fingerprint, RasterKey } from '../identity.js';

export type MsdfBakerOptions = MsdfOptions | undefined;

export interface MsdfBakerRequest {
  readonly sourceFingerprint: Fingerprint;
  readonly fontFaceIndex: number;
  readonly glyphCount: number;
  readonly shapingFingerprint: Fingerprint;
  readonly rasterKey: RasterKey;
  readonly packaging: {
    readonly artifact: 'embedded' | 'external';
  };
  readonly descriptor: MsdfDescriptor;
}

export interface MsdfBakerCoreRequest {
  readonly source: Uint8Array;
  readonly request: MsdfBakerRequest;
  readonly onProgress?: BakeProgressListener;
}

export interface MsdfBakerCore {
  bake(request: MsdfBakerCoreRequest): RasterBakeArtifact<'msdf'>;
}

export type MsdfBakerWasmSource = BufferSource | WebAssembly.Module;

export class MsdfBakeError extends GlyphError<'bake-failed'> {
  readonly reason: string;
  readonly path: string | undefined;

  constructor(error: SerializedBakeError) {
    super('bake-failed', error.message);
    this.name = 'MsdfBakeError';
    this.reason = error.code;
    this.path = error.path;
  }
}

export async function createMsdfBaker(source: MsdfBakerWasmSource): Promise<MsdfBakerCore> {
  let listener: BakeProgressListener | undefined;
  const instance = await instantiateWasm(source, {
    env: {
      pmndrs_glyph_bake_progress(completed: number, total: number) {
        listener?.({ stage: 'raster', phase: 'rasterizing', completed, total });
      },
    },
  });
  const core = createMsdfBakerFromInstance(instance);
  return {
    bake(request) {
      listener = request.onProgress;
      try {
        return core.bake(request);
      } finally {
        listener = undefined;
      }
    },
  };
}

export function createMsdfBakerFromInstance(instance: WebAssembly.Instance): MsdfBakerCore {
  const abi = msdfBakerAbi;
  const directAbi: DirectRasterBakerAbi = {
    memory: abi.memory,
    functions: {
      allocate: {
        export: abi.functions.allocate,
        parameters: ['byteLength'],
        result: 'pointer',
      },
      deallocate: {
        export: abi.functions.deallocate,
        parameters: ['pointer', 'byteLength'],
      },
      bake: abi.artifactBaker.functions.bake,
      responseByteLength: abi.artifactBaker.functions.responseByteLength,
    },
    response: abi.artifactBaker.response,
    segmented: {
      chunkByteLength: abi.artifactBaker.response.segmented.chunkByteLength,
      unavailableStatus: abi.artifactBaker.response.segmented.unavailableStatus,
      functions: {
        status: abi.artifactBaker.functions.segmentedStatus,
        metadataPointer: abi.artifactBaker.functions.segmentedMetadataPointer,
        metadataByteLength: abi.artifactBaker.functions.segmentedMetadataByteLength,
        artifactCount: abi.artifactBaker.functions.segmentedArtifactCount,
        artifactByteLength: abi.artifactBaker.functions.segmentedArtifactByteLength,
        chunkPointer: abi.artifactBaker.functions.segmentedChunkPointer,
        chunkByteLength: abi.artifactBaker.functions.segmentedChunkByteLength,
        release: abi.artifactBaker.functions.releaseSegmentedResponse,
      },
    },
  };
  return createDirectRasterBakerFromInstance<MsdfBakerRequest, 'msdf'>(instance, directAbi, {
    label: 'MSDF baker',
    kind: MSDF_KIND,
    extension: MSDF_EXTENSION,
    version: MSDF_FORMAT_VERSION,
    pageFormat: 'rgba8unorm',
    createError: (error) => new MsdfBakeError(error),
  });
}

export function msdfBakerFromCore(core: MsdfBakerCore): RasterBakerModule<'msdf', MsdfBakerOptions, MsdfDescriptor> {
  return {
    kind: MSDF_KIND,
    extension: MSDF_EXTENSION,
    version: MSDF_FORMAT_VERSION,
    descriptor: msdfDescriptor,
    async bake(request: RasterBakeRequest<MsdfDescriptor>) {
      request.signal?.throwIfAborted();
      const result = core.bake({
        source: request.font.source,
        ...(request.onProgress === undefined ? {} : { onProgress: request.onProgress }),
        request: {
          sourceFingerprint: request.font.sourceFingerprint,
          fontFaceIndex: request.font.fontFaceIndex,
          glyphCount: request.font.glyphCount,
          shapingFingerprint: request.font.shapingFingerprint,
          rasterKey: request.rasterKey,
          packaging: request.packaging,
          descriptor: request.descriptor,
        },
      });
      request.signal?.throwIfAborted();
      return result;
    },
  };
}

async function loadDefaultMsdfBaker(): Promise<ReturnType<typeof msdfBakerFromCore>> {
  const wasmUrl = new URL('../../dist/mtsdf-baker.wasm', import.meta.url);
  let source: BufferSource | WebAssembly.Module;
  if (wasmUrl.protocol === 'file:') {
    const { readFile } = await import('node:fs/promises');
    source = await readFile(wasmUrl);
  } else {
    const response = await fetch(wasmUrl);
    if (!response.ok) throw new Error(`Unable to load MSDF baker Wasm (${response.status})`);
    source = await compileWasmResponse(response);
  }
  return msdfBakerFromCore(await createMsdfBaker(source));
}

const defaultMsdfBaker = cacheSuccessfulPromise(loadDefaultMsdfBaker);

export const msdfBaker: RasterBakerModule<'msdf', MsdfBakerOptions, MsdfDescriptor> = {
  kind: MSDF_KIND,
  extension: MSDF_EXTENSION,
  version: MSDF_FORMAT_VERSION,
  descriptor: msdfDescriptor,
  async bake(request) {
    return (await defaultMsdfBaker()).bake(request);
  },
};

export default msdfBaker;
